# Site settings
title:       Cody's blog
email:       int64ago@gmail.com
author:      Cody Chan
description: "Cody's blog -- Keep It Simple, Stupid!"
baseurl:     ""
url:         "https://int64ago.org"


# Build settings
markdown:     kramdown
kramdown:
  input: GFM
permalink:    pretty
paginate:     8
sass:
  compressed: true
gems:
  - jekyll-sitemap
  - jekyll-paginate
